/*
# QR Attendance System — Full Schema

## Summary
Creates all tables required for the QR-based attendance system with three user roles:
Admin, Faculty, and Student. Each user authenticates via Supabase Auth and has a
corresponding profile. Faculty can generate time-limited QR sessions; students scan
them to mark attendance. Admins manage all data.

## New Tables

### profiles
Extends auth.users with display name, role, photo URL, and contact info.
- id (uuid, FK → auth.users, PK)
- full_name (text)
- role (text: 'admin' | 'faculty' | 'student')
- photo_url (text, nullable)
- phone (text, nullable)
- created_at (timestamptz)

### students
Student-specific data linked to profiles.
- id (uuid, PK, FK → profiles)
- reg_no (text, unique)
- course (text)
- section (text)
- semester (int)
- department (text)

### faculty
Faculty-specific data linked to profiles.
- id (uuid, PK, FK → profiles)
- employee_id (text, unique)
- department (text)
- designation (text)

### subjects
Subjects taught by faculty members.
- id (uuid, PK)
- subject_code (text, unique)
- subject_name (text)
- faculty_id (uuid, FK → faculty)
- section (text)
- semester (int)
- department (text)
- created_at (timestamptz)

### qr_sessions
Time-limited QR sessions generated by faculty for attendance.
- id (uuid, PK)
- subject_id (uuid, FK → subjects)
- faculty_id (uuid, FK → profiles)
- qr_token (text, unique) — the encoded value inside the QR
- generated_at (timestamptz)
- expires_at (timestamptz)
- is_active (boolean)

### attendance_records
Individual attendance entries per student per QR session.
- id (uuid, PK)
- session_id (uuid, FK → qr_sessions)
- student_id (uuid, FK → profiles)
- marked_at (timestamptz)
- status (text: 'present' | 'absent' | 'leave')

## Security
- RLS enabled on all tables.
- Profiles: users read/update own; admin reads all.
- Students/Faculty: owner can read/update own; admin full control.
- Subjects: faculty can CRUD own; all authenticated can read; admin full control.
- QR sessions: faculty creates own; all authenticated can read active sessions.
- Attendance: students insert own (once per session); faculty/admin can read all.
*/

-- ──────────────────────────────────────────
-- profiles
-- ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   text NOT NULL DEFAULT '',
  role        text NOT NULL DEFAULT 'student' CHECK (role IN ('admin','faculty','student')),
  photo_url   text,
  phone       text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
CREATE POLICY "profiles_select_own" ON profiles FOR SELECT
  TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_select_admin" ON profiles;
CREATE POLICY "profiles_select_admin" ON profiles FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "profiles_insert_own" ON profiles;
CREATE POLICY "profiles_insert_own" ON profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON profiles;
CREATE POLICY "profiles_update_own" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_admin" ON profiles;
CREATE POLICY "profiles_update_admin" ON profiles FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS "profiles_delete_admin" ON profiles;
CREATE POLICY "profiles_delete_admin" ON profiles FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ──────────────────────────────────────────
-- students
-- ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS students (
  id          uuid PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  reg_no      text UNIQUE NOT NULL,
  course      text NOT NULL DEFAULT '',
  section     text NOT NULL DEFAULT '',
  semester    int  NOT NULL DEFAULT 1,
  department  text NOT NULL DEFAULT ''
);

ALTER TABLE students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "students_select_auth" ON students;
CREATE POLICY "students_select_auth" ON students FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "students_insert_own" ON students;
CREATE POLICY "students_insert_own" ON students FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "students_insert_admin" ON students;
CREATE POLICY "students_insert_admin" ON students FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "students_update_own" ON students;
CREATE POLICY "students_update_own" ON students FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "students_update_admin" ON students;
CREATE POLICY "students_update_admin" ON students FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS "students_delete_admin" ON students;
CREATE POLICY "students_delete_admin" ON students FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ──────────────────────────────────────────
-- faculty
-- ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS faculty (
  id           uuid PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  employee_id  text UNIQUE NOT NULL,
  department   text NOT NULL DEFAULT '',
  designation  text NOT NULL DEFAULT 'Assistant Professor'
);

ALTER TABLE faculty ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "faculty_select_auth" ON faculty;
CREATE POLICY "faculty_select_auth" ON faculty FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "faculty_insert_own" ON faculty;
CREATE POLICY "faculty_insert_own" ON faculty FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "faculty_insert_admin" ON faculty;
CREATE POLICY "faculty_insert_admin" ON faculty FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

DROP POLICY IF EXISTS "faculty_update_own" ON faculty;
CREATE POLICY "faculty_update_own" ON faculty FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "faculty_update_admin" ON faculty;
CREATE POLICY "faculty_update_admin" ON faculty FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS "faculty_delete_admin" ON faculty;
CREATE POLICY "faculty_delete_admin" ON faculty FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ──────────────────────────────────────────
-- subjects
-- ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS subjects (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_code  text UNIQUE NOT NULL,
  subject_name  text NOT NULL,
  faculty_id    uuid REFERENCES faculty(id) ON DELETE SET NULL,
  section       text NOT NULL DEFAULT '',
  semester      int  NOT NULL DEFAULT 1,
  department    text NOT NULL DEFAULT '',
  created_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "subjects_select_auth" ON subjects;
CREATE POLICY "subjects_select_auth" ON subjects FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "subjects_insert_admin" ON subjects;
CREATE POLICY "subjects_insert_admin" ON subjects FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty'))
  );

DROP POLICY IF EXISTS "subjects_update_admin" ON subjects;
CREATE POLICY "subjects_update_admin" ON subjects FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty')))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty')));

DROP POLICY IF EXISTS "subjects_delete_admin" ON subjects;
CREATE POLICY "subjects_delete_admin" ON subjects FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ──────────────────────────────────────────
-- qr_sessions
-- ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS qr_sessions (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_id    uuid REFERENCES subjects(id) ON DELETE CASCADE,
  faculty_id    uuid REFERENCES profiles(id) ON DELETE CASCADE,
  qr_token      text UNIQUE NOT NULL,
  generated_at  timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL,
  is_active     boolean NOT NULL DEFAULT true
);

ALTER TABLE qr_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "qr_sessions_select_auth" ON qr_sessions;
CREATE POLICY "qr_sessions_select_auth" ON qr_sessions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "qr_sessions_insert_faculty" ON qr_sessions;
CREATE POLICY "qr_sessions_insert_faculty" ON qr_sessions FOR INSERT
  TO authenticated WITH CHECK (
    auth.uid() = faculty_id AND
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty'))
  );

DROP POLICY IF EXISTS "qr_sessions_update_faculty" ON qr_sessions;
CREATE POLICY "qr_sessions_update_faculty" ON qr_sessions FOR UPDATE
  TO authenticated
  USING (auth.uid() = faculty_id OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (auth.uid() = faculty_id OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS "qr_sessions_delete_faculty" ON qr_sessions;
CREATE POLICY "qr_sessions_delete_faculty" ON qr_sessions FOR DELETE
  TO authenticated USING (
    auth.uid() = faculty_id OR
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ──────────────────────────────────────────
-- attendance_records
-- ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS attendance_records (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  uuid NOT NULL REFERENCES qr_sessions(id) ON DELETE CASCADE,
  student_id  uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  marked_at   timestamptz NOT NULL DEFAULT now(),
  status      text NOT NULL DEFAULT 'present' CHECK (status IN ('present','absent','leave')),
  UNIQUE (session_id, student_id)
);

ALTER TABLE attendance_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "attendance_select_auth" ON attendance_records;
CREATE POLICY "attendance_select_auth" ON attendance_records FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "attendance_insert_student" ON attendance_records;
CREATE POLICY "attendance_insert_student" ON attendance_records FOR INSERT
  TO authenticated WITH CHECK (
    auth.uid() = student_id
  );

DROP POLICY IF EXISTS "attendance_insert_faculty_admin" ON attendance_records;
CREATE POLICY "attendance_insert_faculty_admin" ON attendance_records FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty'))
  );

DROP POLICY IF EXISTS "attendance_update_faculty_admin" ON attendance_records;
CREATE POLICY "attendance_update_faculty_admin" ON attendance_records FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty')))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','faculty')));

DROP POLICY IF EXISTS "attendance_delete_admin" ON attendance_records;
CREATE POLICY "attendance_delete_admin" ON attendance_records FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ──────────────────────────────────────────
-- Indexes
-- ──────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_attendance_session ON attendance_records(session_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance_records(student_id);
CREATE INDEX IF NOT EXISTS idx_qr_sessions_faculty ON qr_sessions(faculty_id);
CREATE INDEX IF NOT EXISTS idx_qr_sessions_subject ON qr_sessions(subject_id);
CREATE INDEX IF NOT EXISTS idx_subjects_faculty ON subjects(faculty_id);
